[package]
name = "kcomprs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
image = "0.25.9"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.10.0-rc.5"
